### PR TITLE
Additional buttons added

### PR DESCRIPTION
**Pull request by kamranbastani**
Select everything, clear and select all of column buttons added

### CODE REVIEW

**Review by GavinLynch04 — APPROVED** [review]
Code looks good to me, make sure to clear out unnecessary comments and code when you merge to main branch

**Review by ryand4 — APPROVED** [review]
Code is good to go. New functions work as intended, nice work!

**Review by oprylord — COMMENTED** [review]
Looks great, everything seems to be in place, good job!

**Review by oprylord — APPROVED** [review]
Looks great, everything seems to be in place, good job!

**Pull request merged**
